apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: CovidDashboard-pvc
  namespace: cdash
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-gp2-retain
