apiVersion: apps/v1
kind: Deployment
metadata:
  name: CovidDashboard
  namespace: cdash
  labels:
    name: CovidDashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      name: CovidDashboard
  template:
    metadata:
      labels:
        name: CovidDashboard
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      containers:
        - name: CovidDashboard
          image: covid-dashboard:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8888
          #command:
            #- /bin/bash
            #- -c
            #- |
              #start.sh jupyter lab --LabApp.token='password' --LabApp.ip='0.0.0.0' --LabApp.allow_root=True
          volumeMounts:
            - name: jupyterlab-data
              mountPath: /home/jovyan
          resources:
            requests:
              memory: 500Mi
              cpu: 250m
      restartPolicy: Always
      volumes:
      - name: jupyterlab-data
        persistentVolumeClaim:
          claimName: jupyterlab-pvc
