apiVersion: apps/v1
kind: Deployment
metadata:
  name: coviddashboard
  #namespace: cdash
  labels:
    name: coviddashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      name: coviddashboard
  template:
    metadata:
      labels:
        name: coviddashboard
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      containers:
        - name: coviddashboard
          image: coviddashboard:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8889
          command:
            - "conda", "run", "-n", "test_geo", "jupyter-lab","--ip=0.0.0.0","--no-browser","--allow-root" "--config=./project/config/jupyter_lab_config.py", "notebooks/CSSE COVID Dashboard.ipynb"
            #- /bin/bash
            #- -c
            #- |
              #start.sh jupyter lab --LabApp.token='password' --LabApp.ip='0.0.0.0' --LabApp.allow_root=True
          #volumeMounts:
           # - name: jupyterlab-data
            #mountPath: /home/data
          resources:
            requests:
              memory: 500Mi
              cpu: 250m
      restartPolicy: Always
      #volumes:
      #- name: jupyterlab-data
        # persistentVolumeClaim:
        #  claimName: coviddashboard-pvc
