apiVersion: v1
kind: Service
metadata:
  name: coviddashboard
  #namespace: cdash
  labels:
    name: coviddashboard
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8889
      protocol: TCP
      name: http
  selector:
    name: jupyterlab
