apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: coviddashboard-pvc
  #namespace: cdash
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard-gp2-retain
