apiVersion: v1
kind: Service
metadata:
  name: CovidDashboard
  namespace: cdash
  labels:
    name: CovidDashboard
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8888
      protocol: TCP
      name: http
  selector:
    name: jupyterlab
